name: Deploy to App Engine

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    name: Build and Deploy to App Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'app-engine-java'

      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet --project=${{ secrets.GCP_PROJECT_ID }}
